import { Interest } from "@/components/interests";

export const ROWS = 5;

export const ALL_INTERESTS: Interest[] = [
  { id: "pizza", label: "Pizza", emoji: "🍕" },
  { id: "photography", label: "Photography", emoji: "📷" },
  { id: "gaming", label: "Gaming", emoji: "🎮" },
  { id: "cooking", label: "Cooking", emoji: "👨‍🍳" },
  { id: "reading", label: "Reading", emoji: "📚" },
  { id: "travel", label: "Travel", emoji: "✈️" },
  { id: "fitness", label: "Fitness", emoji: "💪" },
  { id: "movies", label: "Movies", emoji: "🎬" },
  { id: "music", label: "Music", emoji: "🎵" },
  { id: "art", label: "Art", emoji: "🎨" },
  { id: "dancing", label: "Dancing", emoji: "💃" },
  { id: "hiking", label: "Hiking", emoji: "🥾" },
  { id: "yoga", label: "Yoga", emoji: "🧘" },
  { id: "gardening", label: "Gardening", emoji: "🌱" },
  { id: "coffee", label: "Coffee", emoji: "☕️" },
  { id: "writing", label: "Writing", emoji: "✍️" },
  { id: "fashion", label: "Fashion", emoji: "👗" },
  { id: "technology", label: "Technology", emoji: "💻" },
  { id: "sports", label: "Sports", emoji: "🏅" },
  { id: "baking", label: "Baking", emoji: "🍰" },
  { id: "astronomy", label: "Astronomy", emoji: "🔭" },
  { id: "pets", label: "Pets", emoji: "🐾" },
  { id: "cycling", label: "Cycling", emoji: "🚴" },
  { id: "drawing", label: "Drawing", emoji: "✏️" },
  { id: "languages", label: "Languages", emoji: "🗣" },
  { id: "meditation", label: "Meditation", emoji: "🧠" },
  { id: "podcasts", label: "Podcasts", emoji: "🎧" },
  { id: "crafts", label: "Crafts", emoji: "🧶" },
  { id: "boardgames", label: "Board Games", emoji: "🎲" },
  { id: "volunteering", label: "Volunteering", emoji: "🤝" },
  { id: "swimming", label: "Swimming", emoji: "🏊" },
  { id: "painting", label: "Painting", emoji: "🖌" },
  { id: "wine", label: "Wine Tasting", emoji: "🍷" },
  { id: "camping", label: "Camping", emoji: "⛺️" },
  { id: "surfing", label: "Surfing", emoji: "🏄" },
  { id: "chess", label: "Chess", emoji: "♟" },
  { id: "photography", label: "Photography", emoji: "📸" },
  { id: "singing", label: "Singing", emoji: "🎤" },
  { id: "skateboarding", label: "Skateboarding", emoji: "🛹" },
  { id: "martial-arts", label: "Martial Arts", emoji: "🥋" },
  { id: "pottery", label: "Pottery", emoji: "🏺" },
  { id: "archery", label: "Archery", emoji: "🏹" },
  { id: "rock-climbing", label: "Rock Climbing", emoji: "🧗" },
  { id: "beer", label: "Beer Crafting", emoji: "🍺" },
  { id: "drumming", label: "Drumming", emoji: "🥁" },
  { id: "magic", label: "Magic Tricks", emoji: "🎩" },
  { id: "origami", label: "Origami", emoji: "📄" },
  { id: "tea", label: "Tea Culture", emoji: "🫖" },
  { id: "calligraphy", label: "Calligraphy", emoji: "🖋" },
  { id: "astronomy", label: "Astronomy", emoji: "🌠" },
];
